"use strict";
const { v4: uuidv4 } = require("uuid");
/** @type {import('sequelize-cli').Migration} */

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Airports",
      [
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara Internasional Yogyakarta",
          city: "Kulon Progo",
          continent: "Asia",
          iata_code: "YIA",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara Internasional Kertajati",
          city: "Majalengka",
          continent: "Asia",
          iata_code: "KJT",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara Internasional Juanda",
          city: "Sidoarjo",
          continent: "Asia",
          iata_code: "SUB",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara H. Asan",
          city: "Kotawaringin Timur",
          continent: "Asia",
          iata_code: "SMQ",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara Internasional APT Pranoto",
          city: "Samarinda",
          continent: "Asia",
          iata_code: "AAP",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name:
            "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan",
          city: "Balikpapan",
          continent: "Asia",
          iata_code: "BPN",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara Internasional Sultan Hasanuddin",
          city: "Maros",
          continent: "Asia",
          iata_code: "UPG",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara Internasional Lombok",
          city: "Mataram",
          continent: "Asia",
          iata_code: "LOP",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Bandar Udara Internasional I Gusti Ngurah Rai",
          city: "Bali",
          continent: "Asia",
          iata_code: "DPS",
          country: "Indonesia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Singapore Changi Airport",
          city: "Singapore",
          continent: "Asia",
          iata_code: "SIN",
          country: "Singapore",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Suvarnabhumi Airport",
          city: "Prakan",
          continent: "Asia",
          iata_code: "BKK",
          country: "Thailand",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Ninoy Aquino International Airport",
          city: "Manila",
          continent: "Asia",
          iata_code: "MNL",
          country: "Philippines",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Kuala Lumpur International Airport",
          city: "Selangor",
          continent: "Asia",
          iata_code: "KUL",
          country: "Malaysia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "EuroAirport Basel Mulhouse Freiburg",
          city: "Basel",
          continent: "Europe",
          iata_code: "BSL",
          country: "Switzerland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Léon-Mba International Airport",
          city: "Libreville",
          continent: "Europe",
          iata_code: "LBV",
          country: "France",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Prince Mohammad bin Abdulaziz International Airport	",
          city: "Medina",
          continent: "Asia",
          iata_code: "MED",
          country: "Saudi Arabia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Lisbon Airport",
          city: "Lisbon",
          continent: "Europe",
          iata_code: "LOP",
          country: "Portugal",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Thunder Bay International Airport",
          city: "Thunder Bay",
          continent: "North America",
          iata_code: "YQT",
          country: "Canada",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airport_id: uuidv4(),
          airport_name: "Los Angeles International Airport",
          city: "Los Angeles",
          continent: "North America",
          iata_code: "LAX",
          country: "United States",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Airports", null, {});
  },
};
