# This is a basic workflow that is manually triggered

name: Deployment run and deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH into VPS and deploy 
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.VPS_HOSTNAME }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: cd my-codelabs-api/; git pull; npm install;pm2 restart finalprojectBE;      
